development: &default
  host: localhost
  adapter: postgresql
  database: react_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: react_test

production:
  <<: *default
  database: react_production
